### ISSUE TITLE
Can not intercept all the log messages with llama_log_set

### ISSUE THREAD

**Issue by dlyz** [SciSharp/LLamaSharp#645]
`NativeApi.llama_log_set` allows to intercept log messages from llama.cpp. But even if you set log callback as early as possible in your code, you will loose a few first messages that are produced by a call to the `llama_backend_init` from here:

https://github.com/SciSharp/LLamaSharp/blob/fa73c8f07c220c42ea26e2d75267564b7fae7250/LLama/Native/NativeApi.Load.cs#L38

For example, this messages aren't handled by the provided callback:

```text
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce <...>
```

In order for `NativeApi.llama_log_set` to be executed, static constructor of `NativeApi` must run. This static constructor will load native library, and also call `llama_backend_init`. So there is no way to set a callback with `NativeApi.llama_log_set` before that.

There is also a slightly related problem with logging, but this time with LLamaSharp messages: logs, activated by `NativeLibraryConfig.Instance.WithLogs()` will always be written to the console and currently there is not way to redirect them elsewhere.

One possible solution is to make an overload for `NativeLibraryConfig.WithLogs()` that accepts an optional `LLamaLogCallback`, and pass it to the `llama_log_set` during the loading before any other function of llama.cpp is called. Also the same callback instance may be used to intercept LLamaSharp initialization log messages, or maybe it should be another dedicated instance, passed along with the one for llama.cpp.

**Comment by martindevans** [comment]
I'll look into this

**Comment by martindevans** [comment]
@dlyz #649 should fix this issue. I'd appreciate your feedback on that PR :)

**Comment by H5L0** [comment]
Hi, I'm afraid this hasn't been fixed yet, on 0.12.0 I redirect the logger before the llama backend initializes and still get this message output to the console.
```
using ILoggerFactory factory = LoggerFactory.Create(builder => builder.AddDebug());
ILogger debugLogger = factory.CreateLogger("Program");

NativeLibraryConfig.Instance.WithLogCallback(debugLogger);
NativeLibraryConfig.Instance.WithCuda(true);
```
that output: 
```
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   no
ggml_cuda_init: CUDA_USE_TENSOR_CORES: yes
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce ...
```
And all other messages are output to the debug window like: 
```
Program: Information: Detected cuda major version 12.
Program: Information: Loaded './runtimes/win-x64/native/cuda12/llama.dll'
Program: Information: llama_model_loader: loaded meta data with 24 key-value pairs and 195 tensors from ...
```

**Comment by H5L0** [comment]
Yes, it works.
![image](https://github.com/SciSharp/LLamaSharp/assets/28242523/56b89d22-a9e1-4fa4-bc43-03fcd127c0a9)

**Comment by martindevans** [comment]
In that case we'll have new nuget packages out soon which include that fix :)

**Comment by martindevans** [comment]
Those binaries have been released, so I'll close this issue now. If it's still a problem please don't hesitate to re-open or create a new issue!
